AppBundle\Entity\User:
  type: entity
  table: users
  options:
    collate: utf8mb4_unicode_ci
    charset: utf8mb4
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 17
    name:
      type: string
      nullable: false
      length: 255
    special:
      type: boolean
      nullable: false
    firstLogin:
      column: firstLogin
      type: datetime
      nullable: true
    lastLogin:
      column: lastLogin
      type: datetime
      nullable: true
    primaryRole:
      column: primaryRole
      type: string
      nullable: true
      length: 255
    email:
      type: string
      nullable: true
      length: 255
    notes:
      type: text
      nullable: true
    website:
      type: string
      nullable: true
      length: 40
    avatar:
      type: text
      nullable: true
  oneToMany:
    votes:
      targetEntity: Vote
      mappedBy: user
    logins:
      targetEntity: Login
      mappedBy: user
  oneToOne:
    loginToken:
      targetEntity: LoginToken
      mappedBy: user
  manyToMany:
    permissions:
      targetEntity: Permission
      inversedBy: users
      joinTable:
        name: user_permissions
        joinColumns:
          userID:
            referencedColumnName: id
        inverseJoinColumns:
          permissionID:
            referencedColumnName: id
  uniqueConstraints:
    steam_id:
      columns: [ username ]
